version: '3'

services:

  wordpress:
    depends_on:
       - db
    image: ucd-wordpress-components-demo
    build: .
    volumes:
      - ./demo-theme:/var/www/html/wp-content/themes/demo-theme
      - media-uploads:/var/www/html/wp-content/uploads
    ports:
       - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_DATABASE: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: define('SCRIPT_DEBUG', true);
  
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  db-data:
  media-uploads: {}