import { html, SelectUtils } from "../../utils";
import { useBlockProps } from '@wordpress/block-editor';
import { useEffect, useState } from "@wordpress/element";
import apiFetch from '@wordpress/api-fetch';
import { decodeEntities } from "@wordpress/html-entities";

export default ( ) => {
  const blockProps = useBlockProps();

  let parent = 0;
  let customParent = 0;

  let postId = SelectUtils.editedPostAttribute('id');
  postId = postId ? postId : 0;
  let p = SelectUtils.editedPostAttribute('parent');
  if ( p ) parent = p;
  const meta = SelectUtils.meta();
  if ( meta.ucd_nav_parent ) customParent = meta.ucd_nav_parent;

  // get subnav items
  const [ subNavItems, setSubNavItems ] = useState( [] );
  useEffect(() => {
    if ( !postId ) return;
    const pathPrefix = '/ucd/subnav/';
    let path = pathPrefix + postId;
    apiFetch( {path} ).then(
      ( r ) => {
        setSubNavItems(r);
      },
      (error) => {
        if ( !parent ) {
          setSubNavItems([]);
          return;
        }
        let path = pathPrefix + parent;
        apiFetch( {path} ).then(
          ( r ) => {
            setSubNavItems(r);
          },
          (error) => {
            setSubNavItems([]);

          })

      })
  }, [postId, parent, customParent]);

  return html`
  <div ...${ blockProps }>
    ${ subNavItems.length == 0 ? html`
    <nav className='sub-nav'>
      <h2 className="sub-nav__title">Autogenerated Sidenav</h2>
      <ul className='sub-nav__menu'>
        <li><a >Links will be autogenerated</a></li>
        <li><a>from the primary nav</a></li>
        <li><a>based on the current page</a></li>
      </ul>
    </nav>
    ` : html`
    <nav className='sub-nav'>
      <h2 className="sub-nav__title">${decodeEntities(subNavItems[0]['title'])}</h2>
      <ul className='sub-nav__menu'>
        ${subNavItems[0].children.map(parent => html`
          <li key=${parent.title}><a>${decodeEntities(parent.title)}</a></li>
        `)}
      </ul>
    </nav>
    `}

  </div>
  `
}
