import { html, SelectUtils } from "../../utils";
import { ToggleControl, SelectControl, TextControl } from '@wordpress/components';
import { PluginDocumentSettingPanel } from '@wordpress/edit-post';
import { useDispatch } from "@wordpress/data";
import { Fragment, useEffect, useState } from "@wordpress/element";
import apiFetch from '@wordpress/api-fetch';

/**
 * This plugin controls how breadcrumbs are constructed for a page
 */
export default () => {

  const meta = SelectUtils.meta();
  const editPost = useDispatch( 'core/editor' ).editPost;
  const isPost = SelectUtils.isPost();

  // get primary nav items
  const [ primaryNavItems, setPrimaryNavItems ] = useState( [] );
  useEffect(() => {
    const path = '/ucd/menu/primary';
    apiFetch( {path} ).then(
      ( r ) => {
        setPrimaryNavItems(r);
      },
      (error) => {
        console.warn('Unable to retrieve nav items')
      })
  }, [])
  const primaryNavSelectItems = (() =>{
    const items = [{ value: 0, label: 'Select a Nav Item' },];
    for (const item of primaryNavItems ) {
      items.push({value: item.id, label: item.title});
      for (const child of item.children ) {
        items.push({value: child.id, label: "- " + child.title});
        for (const grandchild of child.children ) {
          items.push({value: grandchild.id, label: "- - " + grandchild.title});
        }
      }
    }
    return items;
  })();

  return html`
    <${Fragment}>
      ${!isPost && html`
        <${PluginDocumentSettingPanel}
          name="ucd-breadcrumbs"
          className="ucd-breadcrumbs"
          icon=${html`<ucdlib-icon style=${{marginLeft: '8px', width: '15px', minWidth: '15px'}} icon="ucd-public:fa-ellipsis"></ucdlib-icon>`}
          title="Breadcrumbs">
            <${ToggleControl}
              label="Hide Breadcrumbs"
              checked=${meta.ucd_hide_breadcrumbs}
              onChange="${ucd_hide_breadcrumbs => {editPost({meta: {ucd_hide_breadcrumbs}})}}" />
            <${TextControl}
              label="Custom Text"
              value=${meta.ucd_custom_breadcrumb_text}
              onChange="${ucd_custom_breadcrumb_text => {editPost({meta: {ucd_custom_breadcrumb_text}})}}"
              help="Instead of the page title, this text is used for the breadcrumb. Unless this page is part of the primary site navigation, then the nav item text is used."
            />
            <${SelectControl}
              label="Custom Parent"
              value=${meta.ucd_nav_parent}
              options=${primaryNavSelectItems}
              help="Overrides autogenerated breadcrumbs for this page and its descendants"
              onChange=${ucd_nav_parent => {editPost({meta: {ucd_nav_parent}})}}
            />
        </${PluginDocumentSettingPanel}>
      `}
    </${Fragment}>
  `;
}
